Repository netguru-code-college/vol3-green, pull requests merged in 2018-08, with the labels that each got.

#2 Feature/catering model
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/catering.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20180824103038_create_caterings.rb
  db/migrate/20180824120902_devise_create_users.rb
  db/schema.rb
  spec/models/catering_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: Work in progress

#5 created controller and index for caterings (and a bit of routes)
  app/controllers/application_controller.rb
  app/controllers/caterings_controller.rb
  app/views/caterings/index.html.erb
  app/views/caterings/show.html.erb
  config/routes.rb
  db/schema.rb
  spec/models/meal_spec.rb
Labels: Ready for review

#10 Created CateringsController boilerplate
  app/assets/javascripts/meals.coffee
  app/assets/stylesheets/meals.scss
  app/controllers/meals_controller.rb
  app/helpers/meals_helper.rb
  config/routes.rb
  spec/controllers/meals_controller_spec.rb
  spec/helpers/meals_helper_spec.rb
Labels: Ready for review

#11 Expand Devise User model & its views
  app/controllers/application_controller.rb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/shared/_links.html.erb
  config/initializers/devise.rb
  db/migrate/20180827084759_add_new_basic_data_to_devise_users.rb
  db/schema.rb
Labels: Ready for review

#8 added readme
  README.md
Labels: Ready for review

#16 OK Sanitizer
  app/controllers/application_controller.rb
  app/sanitizers/catering_sanitizer.rb
  app/sanitizers/user_sanitizer.rb
  config/application.rb
Labels: Review done

#17 Created views for MealsController; wrote basic business logic
  app/controllers/meals_controller.rb
  app/views/caterings/index.html.erb
  app/views/meals/edit.html.erb
  app/views/meals/index.html.erb
  app/views/meals/show.html.erb
  db/schema.rb
Labels: Review done

#24 Removed redundant routes
  config/routes.rb
Labels: Review done

#26 Catering can now enter more data during signup & on the profile edit page
  app/sanitizers/catering_sanitizer.rb
  app/views/caterings/registrations/edit.html.erb
  app/views/caterings/registrations/new.html.erb
  app/views/caterings/shared/_links.html.erb
Labels: Review done
